on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: A job to run the build
    steps:
      - uses: actions/checkout@v6
      - name: Build step
        uses: ./
      - uses: actions/upload-artifact@v7
        with:
          path: mingw-w64-v14.0.0.tar.gz
          archive: false
      - uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: mingw-w64-v14.0.0.tar.gz
